//-
//      locations.js
//-

const soundingLocations = [
    { filename:'Arlanda', name:'Stockholm/Arlanda Airport', icao:'ESSA', lat:'59.75', lon:'18.0' },
    { filename:'Gallivare', name:'G&auml;llivare Lapland Airport', icao:'ESNG', lat:'67.25', lon:'20.75' },
    { filename:'Lycksele', name:'Lycksele Airport', icao:'ESNL', lat:'64.5', lon:'18.75' },
    { filename:'Orsa', name:'Orsa/Tallhed Airfield', icao:'ESNR', lat:'61.0', lon:'14.75' },
    { filename:'Jonkoping', name:'J&ouml;nk&ouml;ping Airport', icao:'ESMX', lat:'57.75', lon:'14.0' },
    { filename:'Hemavan', name:'Hemavan T&auml;rnaby Airport', icao:'ESUT', lat:'65.75', lon:'15.0' },
    { filename:'Sundsvall', name:'Sundsvall-Timr&aring; Airport', icao:'ESNN', lat:'62.5', lon:'17.5' },
    { filename:'Visby', name:'Visby Airport', icao:'ESSV', lat:'57.75', lon:'18.5' },
    { filename:'Kastrup', name:'Copenhagen Airport, Kastrup', icao:'EKCH', lat:'55.75', lon:'12.0' },
    { filename:'Karup', name:'Karup/Midtjyllands Airport', icao:'EKKA', lat:'56.25', lon:'9.0' },
    { filename:'Gardemoen', name:'Oslo/Gardermoen Airport', icao:'ENGM', lat:'60.25', lon:'11.0' },
    { filename:'Bergen', name:'Bergen/Flesland Airport', icao:'ENBR', lat:'60.25', lon:'5.25' },
    { filename:'Trondheim', name:'Trondheim/V&aelig;rnes Airport', icao:'ENVA', lat:'63.50',lon:'11.0' },
    { filename:'Tromso', name:'Troms&oslash; Aiport', icao:'EFJO', lat:'69.75', lon:'19.0' },
    { filename:'Helsinki', name:'Helsinki/Vantaa Airport', icao:'EFHK', lat:'60.25', lon:'25.0' },
    { filename:'Oulu', name:'Oulu Airport', icao:'EFOU', lat:'65.0', lon:'25.25' },
    { filename:'Jyvaskyla', name:'Jyv&auml;skyl&auml; Airport', icao:'EFJY', lat:'62.25', lon:'25.75' },
    { filename:'Ivalo', name:'Ivalo Airport', icao:'EFRO', lat:'68.5', lon:'27.5' },
    { filename:'Tallinn', name:'Tallinn/Ulemiste Airport', icao:'EETN', lat:'59.25', lon:'25.0' },
    { filename:'Riga', name:'Riga International Airport', icao:'EVRA', lat:'57.0', lon:'24.0' },
    { filename:'Vilnius', name:'Vilnius International Airport', icao:'EYVI', lat:'54.75', lon:'25.25' },
    { filename:'Hamburg', name:'Hamburg Airport', icao:'EDDH', lat:'53.75', lon:'10.0' },
    { filename:'Berlin', name:'Berlin/Sch&ouml;nefeld International Airport', icao:'EDDB', lat:'52.25', lon:'13.5' },
    { filename:'Gdansk', name:'Gda&nacute;sk Lech Wa&lstrok;&eogon;sa Airport', icao:'EPGD', lat:'54.5', lon:'18.25' },
    { filename:'Warszawa', name:'Warsaw/Ok&eogon;cie Fr&eacute;d&eacute;ric Chopin Airport', icao:'EPWA', lat:'52.25', lon:'21.0' },
    { filename:'Heathrow', name:'London Heathrow Airport', icao:'EGLL', lat:'51.5', lon:'-0.5' },
    { filename:'CharlesDeGaulle', name:'Paris/Charles de Gaulle Airport', icao:'LFPG', lat:'49.0', lon:'2.5' },
    { filename:'Schiphol', name:'Amsterdam Airport Schiphol', icao:'EHAM', lat:'52.25', lon:'4.75' },
    { filename:'Prague', name:'Prague/V&aacute;clav Havel Airport', icao:'LKPR', lat:'50.0', lon:'14.25' },
    { filename:'Glasgow', name:'Glasgow Airport', icao:'EGPF', lat:'55.75', lon:'-4.5' },
    { filename:'Kyiv', name:'Kyiv International Airport', icao:'UKKK', lat:'50.5', lon:'30.5' },
    { filename:'Vienna', name:'Vienna International Airport', icao:'LOWW', lat:'48.0', lon:'16.5' },
    { filename:'Zurich', name:'Zurich Airport', icao:'LSZH', lat:'47.5', lon:'8.5' },
    { filename:'Bucharest', name:'Bucharest/Henri Coandă International Airport', icao:'LROP', lat:'44.5', lon:'26.0' },
    { filename:'Sarajevo', name:'Sarajevo International Airport', icao:'LQSA', lat:'43.75', lon:'18.25' },
    { filename:'Rome', name:'Rome/Leonardo da Vinci International Airport', icao:'LIRF', lat:'41.75', lon:'12.25' },
    { filename:'Bordeaux', name:'Bordeaux Airport', icao:'LFBD', lat:'44.75', lon:'-0.75' },
    { filename:'Madrid', name:'Madrid-Barajas Airport', icao:'LEMD', lat:'40.5', lon:'-3.5' },
    { filename:'BothnianSea', name:'Bothnian sea', icao:'NN', lat:'61.75', lon:'19.5' },
    { filename:'NorthSea', name:'North sea', icao:'NN', lat:'56.25', lon:'4.25' },
    { filename:'NorwegianSea', name:'Norwegian sea', icao:'NN', lat:'65.75', lon:'6.25' }
];