//-
//      locations.js
//-

const soundingLocations = [
    { filename:'Arlanda', name:'Stockholm/Arlanda Airport', icao:'ESSA', lat:'59.75', lon:'18.0' },
    { filename:'Landvetter', name:'G&ouml;teborg/Landvetter Airport', icao:'ESGG', lat:'57.75', lon:'12.25' },
    { filename:'Ostersund', name:'&Aring;re-&Ouml;stersund Airport', icao:'ESNZ', lat:'63.25',lon:'14.5' },
    { filename:'Gallivare', name:'G&auml;llivare Lapland Airport', icao:'ESNG', lat:'67.25', lon:'20.75' },
    { filename:'Umea', name:'Ume&aring; Airport', icao:'ESNU', lat:'63.75', lon:'20.25' },
    { filename:'Orsa', name:'Orsa/Tallhed Airfield', icao:'ESNR', lat:'61.0', lon:'14.75' },
    { filename:'Vaxjo', name:'V&auml;xj&ouml;/Kronoberg Airport', icao:'ESMX', lat:'57.0', lon:'14.75' },
    { filename:'Arvidsjaur', name:'Arvidsjaur Airport', icao:'ESNX', lat:'65.5', lon:'19.25' },
    { filename:'Visby', name:'Visby Airport', icao:'ESSV', lat:'57.75', lon:'18.5' },
    { filename:'Orebro', name:'&Ouml;rebro Airport', icao:'ESOE', lat:'59.25', lon:'15.0' },
    { filename:'Kastrup', name:'Copenhagen Airport, Kastrup', icao:'EKCH', lat:'55.75', lon:'12.0' },
    { filename:'Karup', name:'Karup/Midtjyllands Airport', icao:'EKKA', lat:'56.25', lon:'9.0' },
    { filename:'Gardemoen', name:'Oslo/Gardermoen Airport', icao:'ENGM', lat:'60.25', lon:'11.0' },
    { filename:'Helsinki', name:'Helsinki/Vantaa Airport', icao:'EFHK', lat:'60.25', lon:'25.0' },
    { filename:'Vaasa', name:'Vaasa/Sein&auml;joki Airport', icao:'EFVA', lat:'63.0', lon:'21.75' },
    { filename:'Turku', name:'Turku Airport', icao:'EFTU', lat:'60.5', lon:'22.25' },
    { filename:'Jyvaskyla', name:'Jyv&auml;skyl&auml; Airport', icao:'EFJY', lat:'62.25', lon:'25.75' },
    { filename:'Rovaniemi', name:'Rovaniemi Airport', icao:'EFRO', lat:'66.5', lon:'25.75' },
    { filename:'Joensuu', name:'Joensuu Aiport', icao:'EFJO', lat:'62.75', lon:'29.50' },
    { filename:'Tallinn', name:'Tallinn/Ulemiste Airport', icao:'EETN', lat:'59.25', lon:'25.0' },
    { filename:'Riga', name:'Riga International Airport', icao:'EVRA', lat:'57.0', lon:'24.0' },
    { filename:'Vilnius', name:'Vilnius International Airport', icao:'EYVI', lat:'54.75', lon:'25.25' },
    { filename:'Hamburg', name:'Hamburg Airport', icao:'EDDH', lat:'53.75', lon:'10.0' },
    { filename:'Berlin', name:'Berlin/Sch&ouml;nefeld International Airport', icao:'EDDB', lat:'52.25', lon:'13.5' },
    { filename:'Gdansk', name:'Gda&nacute;sk Lech Wa&lstrok;&eogon;sa Airport', icao:'EPGD', lat:'54.5', lon:'18.25' },
    { filename:'Warszawa', name:'Warsaw/Ok&eogon;cie Fr&eacute;d&eacute;ric Chopin Airport', icao:'EPWA', lat:'52.25', lon:'21.0' },
    { filename:'StPetersburg', name:'St Petersburg/Pulkovo', icao:'ULLI', lat:'59.75', lon:'30.25' },
    { filename:'Heathrow', name:'London Heathrow Airport', icao:'EGLL', lat:'51.5', lon:'-0.5' },
    { filename:'CharlesDeGaulle', name:'Paris/Charles de Gaulle Airport', icao:'LFPG', lat:'49.0', lon:'2.5' },
    { filename:'Schiphol', name:'Amsterdam Airport Schiphol', icao:'EHAM', lat:'52.25', lon:'4.75' },
    { filename:'Prague', name:'Prague/V&aacute;clav Havel Airport', icao:'LKPR', lat:'50.0', lon:'14.25' },
    { filename:'BothnianSea', name:'Bothnian sea', icao:'NN', lat:'61.75', lon:'19.5' },
    { filename:'NorthSea', name:'North sea', icao:'NN', lat:'56.25', lon:'4.25' },
    { filename:'NorwegianSea', name:'Norwegian sea', icao:'NN', lat:'65.75', lon:'6.25' }
];